### ISSUE TITLE
Error in bpl when adding. 

### ISSUE THREAD

**Issue by Westoner** [War3Evo/gtDelphi#1]
Hi

I get an error (Read of address 0000000E) when running any application with this component added.
Any help appreciated.

Thanks
Chris

**Comment by War3Evo** [comment]
Which one?  There are two separate components. CSV and Command prompt.

**Comment by War3Evo** [comment]
> Hi
> 
> I get an error (Read of address 0000000E) when running any application with this component added.
> Any help appreciated.
> 
> Thanks
> Chris

Which one? There are two separate components. CSV and Command prompt.

My current work around when Delphi does that is to restart Delphi. Still curious on which one of those components your having issues with.

The latest version for gtCommandPrompt.pas is in the develop branch.

**Comment by War3Evo** [comment]
Fixed Access Violation when opening an program that has gtCommandPrompt.pas component on it.

**Comment by Westoner** [comment]
Excellent news...Thank you

Is there a way to send commands through the Write command, such as CTRL+c?

Thanks
